modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Phatdog731/phats_progression/issues"
license = "MIT"

[[mods]]
modId = "phats_progression"
version = "${version}"
displayName = "Phat's Progression Framework"
authors = "Phatdog731"
description = '''
A modpack-configurable mining tier progression system that extends the vanilla tier system past netherite. Define which blocks require which tools entirely through config.
'''

[[dependencies.phats_progression]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.phats_progression]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.phats_progression]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "phats_progression.mixins.json"